name: deploy
on: [push]
jobs:
  setup-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Update theme
        run: git submodule update --init --recursive
      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.83.1"
      - name: Build
        run: hugo

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.REVERSE_PROXY_SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Deploy with rsync
        run: rsync -avz public/* ${{ secrets.SSH_USER }}@${{ secrets.REVERSE_PROXY_IP }}:/var/www/zimmerman.dev/